### ISSUE TITLE
scripts insert two or more rules,will crash

### ISSUE THREAD

**Issue by edwin--zhao** [ldx/python-iptables#157] opened 2015-08-11 05:59 UTC
```
#!/usr/bin/python
#config iptables rule
#Author: edwin
#Date: 2015-08-06

import iptc
import time

OFFICE_NETWORK = "172.16.0.0/16"

def test(dst, port, comment):
    print "Rule"
    rule = iptc.Rule()
    print "Prerouting"
    chain = iptc.Chain(iptc.Table(iptc.Table.NAT), "PREROUTING")
    rule.src = OFFICE_NETWORK
    rule.dst = "%s/32" % dst
    rule.protocol = "tcp"
    print "Multiport"
    match = iptc.Match(rule, "multiport")
    #match = iptc.Match(rule, "tcp")
    match.dports = str(port)
    print "Match"
    rule.add_match(match)
    print "Comment"
    comt = rule.create_match("comment")
    comt.comment = comment
    print "ACCEPT"
    rule.target = iptc.Target(rule, "ACCEPT")
    print "Insert"
    chain.insert_rule(rule)


if __name__ == "__main__":
    #main()
    rules = [{"ip":"10.20.1.49","port":"47000","comment":"_0000_ test1"},
	{"ip":"10.20.1.49","port":"48000","comment":"_0001_ test2"},
	{"ip":"10.20.1.49","port":"49000","comment":"_0003_ test3"},
	{"ip":"10.20.1.49","port":"46000","comment":"_0004_ test4"},
	]
#    for i in rules:
#        dst = i["ip"]
#        port = i["port"]
#        comment = i["comment"]
#    	 test(dst, port, comment)
    #pdb.set_trace()
    print 0
    dst = rules[0]["ip"]
    port = rules[0]["port"]
    comment = rules[0]["comment"]
    test(dst, port, comment)
    print 1
    dst = rules[1]["ip"]
    port = rules[1]["port"]
    comment = rules[1]["comment"]
    test(dst, port, comment)
    print 2
    dst = rules[2]["ip"]
    port = rules[2]["port"]
    comment = rules[2]["comment"]
    test(dst, port, comment)
    print 3
    dst = rules[3]["ip"]
    port = rules[3]["port"]
    comment = rules[3]["comment"]
    test(dst, port, comment)
```

run scripts get this:

```
0
Rule
Prerouting
Multiport
Match
Comment
ACCEPT
Insert
1
Rule
Prerouting
Multiport
Match
Comment
ACCEPT
Insert
2
Rule
Prerouting
Multiport
Match
Comment
ACCEPT
Insert
3
Rule
Prerouting
Multiport
Match
Comment
ACCEPT
Insert
*** glibc detected *** python: free(): invalid pointer: 0x00007f4ae839c860 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x75e66)[0x7f4af2878e66]
/usr/lib64/libffi.so.5(ffi_call_unix64+0x4c)[0x7f4aeb926dac]
/usr/lib64/libffi.so.5(ffi_call+0x214)[0x7f4aeb926b34]
/usr/lib64/python2.6/lib-dynload/_ctypes.so(_CallProc+0x394)[0x7f4aebb3a074]
/usr/lib64/python2.6/lib-dynload/_ctypes.so(+0xa3a2)[0x7f4aebb333a2]
/usr/lib64/libpython2.6.so.1.0(PyObject_Call+0x53)[0x3b01e43c63]
/usr/lib64/libpython2.6.so.1.0(PyEval_EvalFrameEx+0x47d4)[0x3b01ed4f74]
/usr/lib64/libpython2.6.so.1.0(PyEval_EvalCodeEx+0x927)[0x3b01ed7657]
/usr/lib64/libpython2.6.so.1.0[0x3b01e6acb0]
/usr/lib64/libpython2.6.so.1.0(PyObject_Call+0x53)[0x3b01e43c63]
/usr/lib64/libpython2.6.so.1.0[0x3b01e566af]
/usr/lib64/libpython2.6.so.1.0(PyObject_Call+0x53)[0x3b01e43c63]
/usr/lib64/libpython2.6.so.1.0(PyEval_CallObjectWithKeywords+0x43)[0x3b01ecfc93]
/usr/lib64/libpython2.6.so.1.0[0x3b01e95ffe]
/usr/lib64/libpython2.6.so.1.0[0x3b01e9a57f]
/usr/lib64/libpython2.6.so.1.0[0x3b01e79e4b]
/usr/lib64/libpython2.6.so.1.0[0x3b01e9a75c]
/usr/lib64/libpython2.6.so.1.0[0x3b01e70aff]
/usr/lib64/libpython2.6.so.1.0(PyDict_Clear+0x10b)[0x3b01e7b9cb]
/usr/lib64/libpython2.6.so.1.0[0x3b01e7ba39]
/usr/lib64/libpython2.6.so.1.0[0x3b01f0071e]
/usr/lib64/libpython2.6.so.1.0(PyGC_Collect+0x24)[0x3b01f00cc4]
/usr/lib64/libpython2.6.so.1.0(Py_Finalize+0x116)[0x3b01ef28a6]
/usr/lib64/libpython2.6.so.1.0(Py_Main+0x596)[0x3b01eff2d6]
/lib64/libc.so.6(__libc_start_main+0xfd)[0x7f4af2821d5d]
python[0x400649]
======= Memory map: ========
00400000-00401000 r-xp 00000000 08:01 271163                             /usr/bin/python
00600000-00602000 rw-p 00000000 08:01 271163                             /usr/bin/python
025ef000-02c5b000 rw-p 00000000 00:00 0                                  [heap]
3b01600000-3b01615000 r-xp 00000000 08:01 130997                         /lib64/libz.so.1.2.3
3b01615000-3b01814000 ---p 00015000 08:01 130997                         /lib64/libz.so.1.2.3
3b01814000-3b01815000 r--p 00014000 08:01 130997                         /lib64/libz.so.1.2.3
3b01815000-3b01816000 rw-p 00015000 08:01 130997                         /lib64/libz.so.1.2.3
3b01e00000-3b01f5d000 r-xp 00000000 08:01 274170                         /usr/lib64/libpython2.6.so.1.0
3b01f5d000-3b0215c000 ---p 0015d000 08:01 274170                         /usr/lib64/libpython2.6.so.1.0
3b0215c000-3b02198000 rw-p 0015c000 08:01 274170                         /usr/lib64/libpython2.6.so.1.0
3b02198000-3b021a6000 rw-p 00000000 00:00 0
3b02200000-3b0221d000 r-xp 00000000 08:01 130999                         /lib64/libselinux.so.1
3b0221d000-3b0241c000 ---p 0001d000 08:01 130999                         /lib64/libselinux.so.1
3b0241c000-3b0241d000 r--p 0001c000 08:01 130999                         /lib64/libselinux.so.1
3b0241d000-3b0241e000 rw-p 0001d000 08:01 130999                         /lib64/libselinux.so.1
3b0241e000-3b0241f000 rw-p 00000000 00:00 0
3b02e00000-3b02e16000 r-xp 00000000 08:01 131001                         /lib64/libgcc_s-4.4.7-20120601.so.1
3b02e16000-3b03015000 ---p 00016000 08:01 131001                         /lib64/libgcc_s-4.4.7-20120601.so.1
3b03015000-3b03016000 rw-p 00015000 08:01 131001                         /lib64/libgcc_s-4.4.7-20120601.so.1
3b03200000-3b03203000 r-xp 00000000 08:01 131014                         /lib64/libcom_err.so.2.1
3b03203000-3b03402000 ---p 00003000 08:01 131014                         /lib64/libcom_err.so.2.1
3b03402000-3b03403000 r--p 00002000 08:01 131014                         /lib64/libcom_err.so.2.1
3b03403000-3b03404000 rw-p 00003000 08:01 131014                         /lib64/libcom_err.so.2.1
3b03e00000-3b03e04000 r-xp 00000000 08:01 131002                         /lib64/libuuid.so.1.3.0
3b03e04000-3b04003000 ---p 00004000 08:01 131002                         /lib64/libuuid.so.1.3.0
3b04003000-3b04004000 rw-p 00003000 08:01 131002                         /lib64/libuuid.so.1.3.0
3b04a00000-3b04bb9000 r-xp 00000000 08:01 281227                         /usr/lib64/libcrypto.so.1.0.1e
3b04bb9000-3b04db8000 ---p 001b9000 08:01 281227                         /usr/lib64/libcrypto.so.1.0.1e
3b04db8000-3b04dd3000 r--p 001b8000 08:01 281227                         /usr/lib64/libcrypto.so.1.0.1e
3b04dd3000-3b04ddf000 rw-p 001d3000 08:01 281227                         /usr/lib64/libcrypto.so.1.0.1e
3b04ddf000-3b04de3000 rw-p 00000000 00:00 0
3b06a00000-3b06a02000 r-xp 00000000 08:01 131011                         /lib64/libkeyutils.so.1.3
3b06a02000-3b06c01000 ---p 00002000 08:01 131011                         /lib64/libkeyutils.so.1.3
3b06c01000-3b06c02000 r--p 00001000 08:01 131011                         /lib64/libkeyutils.so.1.3
3b06c02000-3b06c03000 rw-p 00002000 08:01 131011                         /lib64/libkeyutils.so.1.3
3d38000000-3d38029000 r-xp 00000000 08:01 130570                         /lib64/libk5crypto.so.3.1
3d38029000-3d38229000 ---p 00029000 08:01 130570                         /lib64/libk5crypto.so.3.1
3d38229000-3d3822a000 r--p 00029000 08:01 130570                         /lib64/libk5crypto.so.3.1
3d3822a000-3d3822b000 rw-p 0002a000 08:01 130570                         /lib64/libk5crypto.so.3.1
3d3822b000-3d3822c000 rw-p 00000000 00:00 0
3d38400000-3d38441000 r-xp 00000000 08:01 130583                         /lib64/libgssapi_krb5.so.2.2
3d38441000-3d38641000 ---p 00041000 08:01 130583                         /lib64/libgssapi_krb5.so.2.2
3d38641000-3d38642000 r--p 00041000 08:01 130583                         /lib64/libgssapi_krb5.so.2.2
3d38642000-3d38644000 rw-p 00042000 08:01 130583                         /lib64/libgssapi_krb5.so.2.2
3d38800000-3d388db000 r-xp 00000000 08:01 130581                         /lib64/libkrb5.so.3.3
3d388db000-3d38ada000 ---p 000db000 08:01 130581                         /lib64/libkrb5.so.3.3
3d38ada000-3d38ae4000 r--p 000da000 08:01 130581                         /lib64/libkrb5.so.3.3
3d38ae4000-3d38ae6000 rw-p 000e4000 08:01 130581                         /lib64/libkrb5.so.3.3
3d38c00000-3d38c0a000 r-xp 00000000 08:01 130567                         /lib64/libkrb5support.so.0.1
3d38c0a000-3d38e09000 ---p 0000a000 08:01 130567                         /lib64/libkrb5support.so.0.1
3d38e09000-3d38e0a000 r--p 00009000 08:01 130567                         /lib64/libkrb5support.so.0.1
3d38e0a000-3d38e0b000 rw-p 0000a000 08:01 130567                         /lib64/libkrb5support.so.0.1Aborted
```

and iptables rule has insert success:

```
-A PREROUTING -s 172.16.0.0/16 -d 10.20.1.49/32 -p tcp -m multiport --dports 46000 -m comment --comment "_0004_ test4" -j ACCEPT
-A PREROUTING -s 172.16.0.0/16 -d 10.20.1.49/32 -p tcp -m multiport --dports 49000 -m comment --comment "_0003_ test3" -j ACCEPT
-A PREROUTING -s 172.16.0.0/16 -d 10.20.1.49/32 -p tcp -m multiport --dports 48000 -m comment --comment "_0001_ test2" -j ACCEPT
-A PREROUTING -s 172.16.0.0/16 -d 10.20.1.49/32 -p tcp -m multiport --dports 47000 -m comment --comment "_0000_ test1" -j ACCEPT
```

if use two function test() test1()，test() run finish ,scripts crash

**Comment by ldx** [comment] 2015-08-11 15:36
Looks like this is the same as #153.

Can you tell me your OS and iptables versions?

**Comment by edwin--zhao** [comment] 2015-08-11 16:39
CentOS release 6.6 (Final)

iptables v1.4.7

>>> print(iptc.version.__version__)
0.10.0-dev

Python 2.6.6

**Comment by edwin--zhao** [comment] 2015-08-11 16:39
CentOS release 6.6 (Final)

iptables v1.4.7

>>> print(iptc.version.__version__)
0.10.0-dev

Python 2.6.6

**Comment by edwin--zhao** [comment] 2015-08-11 16:42
before comment ,I google find #153 ,then update python-iptables from git

**Comment by serfer2** [comment] 2015-08-18 15:49
Hi,

same error when executing script detailed in this module doc:
https://github.com/ldx/python-iptables#chains-and-tables

Details:
 - SO:  CentOS release 6.7 (Final)
 - iptc version:  0.9.0  (installed from pip install python-iptables)
 - Iptables:  iptables-1.4.7

**Comment by serfer2** [comment] 2015-08-19 15:23
Any solution for this issue?

**Comment by ldx** [comment] 2015-08-19 15:39
@serfer2 works with newer versions of iptables. I'm looking into fixing it with 1.4.7, but it will take a bit of time.

**Comment by serfer2** [comment] 2015-08-19 16:05
Thank you so much @Idx ;-)

**Comment by renecunningham** [comment] 2015-08-26 05:37
I can confirm I'm seeing this on CentOS 6 but not CentOS 7.

See gist below for triggering bug on CentOS 6.4. I can also confirm bug exists with CentOS 6.7.

https://gist.github.com/renecunningham/eef7345e7c1fd461b151

Work around for me right now is to revert to 0.8.0 by pip installing directly from github using e4a0ad.

```
pip install git+git://github.com/ldx/python-iptables.git@e4a0ad3c7081081d6eac264c6ae2082a21d9b7e5
```

See gist below for work around too.

https://gist.github.com/renecunningham/102b78b8704b3666aee0

**Comment by ldx** [comment] 2015-08-30 19:24
@edwin--zhao @serfer2 @renecunningham this has been fixed in latest master, let me know if you still experience any problems.

**Closed** 2015-08-30 19:23 UTC

**Comment by edwin--zhao** [comment] 2015-09-01 01:43
@ldx  ,I am sorry,last week I changed jobs, I use iptables-python in express company.The new company temporarily no environment test

**Comment by ldx** [comment] 2015-09-01 10:24
No worries, good luck with your new gig!
