### ISSUE TITLE
can't commit: b'Resource temporarily unavailable'

### ISSUE THREAD

**Issue by perolwy** [ldx/python-iptables#121] opened 2014-12-01 17:02 UTC
Sometimes commit() throws exception if commits aren't far from each other. Looks like it requires refresh(). The same problem if I edit iptables calling the iptables binary before commit() is called.

#BAD
#get chain from table
table = iptc.Table(iptc.Table.NAT)
table.autocommit = False
chain = iptc.Chain(table, 'PREROUTING')
#delete old rules
for rule in chain.rules:
	chain.delete_rule(rule)
#commit updates
table.commit()
#create rule
rule = iptc.Rule()
#set it up
...
#add rule
chain.insert_rule(rule)
#commit updates
table.commit()

#GOOD
#get chain from table
table = iptc.Table(iptc.Table.NAT)
table.refresh()
table.autocommit = False
chain = iptc.Chain(table, 'PREROUTING')
#delete old rules
for rule in chain.rules:
	chain.delete_rule(rule)
#commit updates
table.commit()
table.refresh()
#create rule
rule = iptc.Rule()
#set it up
...
#add rule
chain.insert_rule(rule)
#commit updates
table.commit()
table.refresh()

**Comment by ldx** [comment] 2015-08-29 21:10
No reply, closing.

**Comment by thejuan** [comment] 2016-01-29 03:54
Adding refresh after a call to commit fixed the issue for me

**Comment by campbellr** [comment] 2016-03-02 20:32
I'm seeing the same problem and even a `refresh()` after a `commit()` doesn't work.

So far iIve had some success with also adding a `refresh()` after instantiating `iptc.Table`

Can we re-open this?

**Comment by ldx** [comment] 2016-03-02 22:42
@campbellr sure. Do you have some example code that reproduces the problem?

**Comment by campbellr** [comment] 2016-03-02 23:05
@ldx thanks. I'll work on stripping my code down into a usable example.

btw, my comment about adding a refresh after insantiating `iptc.Table` was actually a fluke. I've hit the problem again since.

**Comment by campbellr** [comment] 2016-03-03 18:46
@ldx here's a script I came up with to reproduce my issue:

https://gist.github.com/campbellr/9b95d9df5b89fafbf4dc

Note that even though the iptables operations are serialized with a lock, the script still fails with a "Resource temporarily unavailable".

That being said, I don't seem to be able to his the problem when using multiple threads, just multiple processes.

**Comment by ldx** [comment] 2016-03-03 22:59
@campbellr that makes sense - iptables uses its own lock internally, and will give you the "Resource temporarily unavailable" error message when you're trying to perform multiple operations at the same time.

Do you have a use case for parallel iptables operations? You might need to serialize these e.g. via a queue and a worker process.

**Comment by ldx** [comment] 2016-03-03 23:48
Another thing that will help: you should call `table.refresh()` before `table.commit()` to make sure your the table is up to date:

    #!/bin/env python3
    import iptc
    import multiprocessing
    
    
    def drop(src, dst):
        """Drop all packets from src to dst"""
        table = iptc.Table(iptc.Table.FILTER)
        rule = iptc.Rule()
        rule.target = iptc.Target(rule, 'DROP')
        rule.src = src
        rule.dst = dst
        chain = iptc.Chain(table, "FORWARD")
        chain.insert_rule(rule)
        table.refresh()
        table.commit()
        table.refresh()
    
    
    def cleanup(ips):
        """Cleanup all the rules for the given ips."""
        table = iptc.Table(iptc.Table.FILTER)
        chain = iptc.Chain(table, "FORWARD")
        for rule in chain.rules:
            src = rule.src.split('/')[0]
            dst = rule.dst.split('/')[0]
            if src in ips or dst in ips:
                chain.delete_rule(rule)
        table.refresh()
        table.commit()
        table.refresh()
    
    
    def process(i):
        """add and then delete a bunch of rules."""
        srcs, dests = subnet_ips(i)
        for src, dst in zip(srcs, dests):
            with lock:
                drop(src, dst)
        with lock:
            cleanup(srcs + dests)
    
    def subnet_ips(i):
        """Generate some bogus ips"""
        srcs = []
        dests = []
        for j in range(10):
            srcs.append('172.{}.0.{}'.format(i, j))
        for j in range(10, 20):
            dests.append('172.{}.0.{}'.format(i, j))
    
        return srcs, dests
    
    
    def init(l):
        """initialze the shared lock for the multiprocessing pool."""
        global lock
        lock = l
    
    
    def main():
        l = multiprocessing.Lock()  # with locking, its a bit harder to reproduce, but still happens
        table = iptc.Table(iptc.Table.FILTER)
        table.autocommit = False
        pool = multiprocessing.Pool(initializer=init, initargs=(l,))
        pool.map(process, range(253))
        pool.close()
        pool.join()
    
    if __name__ == '__main__':
        for x in range(100):
            print x
            main()

**Comment by campbellr** [comment] 2016-03-03 23:49
If you look closely at my example I actually do serialize the operations with a multiprocessing.Lock, which is why I'm confused.

Of course, I could also be doing it wrong...

**Comment by ldx** [comment] 2016-03-04 00:03
@campbellr correct, pls see the code example above - this works for me without errors.

**Comment by campbellr** [comment] 2016-03-04 02:23
That solution works for me too, thanks! (although i don't really understand why)

My use case is probably not that common. I have a suite of tests that uses iptables to simulate network partitions between docker containers and I ran into this attempting to parallelize those tests.

**Comment by ldx** [comment] 2016-03-04 18:52
The two main changes in my code:
- Disable `autocommit` when starting up. No reason to enable it if before a `commit()` it always gets disabled.
- Calling `refresh()` makes sure that we don't have a "stale" state cached in iptables before a commit.

**Comment by ldx** [comment] 2016-03-04 18:52
Closing since this seems to be fixed.

**Closed by ldx** 2016-03-04 18:52 UTC

**Comment by yskomur** [comment] 2016-10-12 13:15
import os
import iptc

for x in range(3):
    t = iptc.Table('filter', autocommit=False)
    c = iptc.Chain(t, 'INPUT')
    r = iptc.Rule(chain=c)
    r.set_in_interface('lo')
    r.target = iptc.Target(r, 'LOG')
    c.insert_rule(r)

    t.commit()
    t.refresh()

    os.system('/sbin/iptables -D INPUT -i lo -j LOG')



when execute external iptables or iptables-restore iptc hang

**Comment by ldx** [comment] 2016-10-15 15:08
@yskomur any reason you call iptables via `os.system()`? It might cause all sorts of problems and interfere with python-iptables.

**Comment by yskomur** [comment] 2016-10-15 18:56
this is working example code..

 my project working with tornadoweb. anybody can change iptables rule from command line while my code is running. not a turning back, restart required.
